# Generated by Django 3.2.20 on 2023-07-25 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_file_uploaad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='file_uploaad',
            new_name='file_upload',
        ),
    ]
